DROP DATABASE Bodegas;

CREATE database Bodegas;

USE Bodegas;

-- Tabla Bodegas

CREATE TABLE BODEGAS (
    IDBODEGAS INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR (100),
    UBICACION VARCHAR (100),
    TELEFONO VARCHAR (100),
    EMAIL VARCHAR (100)
);

-- Tabla Proveedores

CREATE TABLE PROVEEDORES (
    IDPROVEEDORES INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR (100),
    TELEFONO VARCHAR (100),
    UBICACION VARCHAR (100),
    TARIFA INT
);

-- Tabla Clientes

CREATE TABLE CLIENTES (
    IDCLIENTES INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR (100),
    REFERENCIA VARCHAR (100),
    CONTACTO VARCHAR (200)
);


-- FOREING KEYS

-- BODEGAS

ALTER TABLE BODEGAS
   ADD CONSTRAINT FK_BODEGAS_PROVEEDORES
   FOREIGN KEY (IDCLIENTES) REFERENCES CLIENTES(IDCLIENTES);
   
-- PROVEEDORES

ALTER TABLE PROVEEDORES
  ADD CONSTRAINT FK_BODEGAS_CLIENTES
  FOREIGN KEY (IDCLIENTES) REFERENCES CLIENTES(IDCLIENTES);
  
  -- CLIENTES
  
  ALTER TABLE CLIENTES
	ADD CONSTRAINT FK_CLIENTES_PROVEEDORES
    FOREIGN KEY (IDPROVEEDORES) REFERENCES PROVEEDORES(IDPROVEEDORES);
    
ALTER TABLE CLIENTES
   ADD CONSTRAINT FK_CLIENTES_BODEGAS
   FOREIGN KEY (IDBODEGAS) REFERENCES BODEGAS(IDBODEGAS);